#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

// Note: map0 - map3 must have their bottom two bits be 2,3,0,1 in that order.  BRK must also start at 0.
#define __GEN_UCODE_ADDR_ENUM(_op) \
_op(kMCA_e_brk0             	)\
_op(kMCA_e_clcsec0              )\
_op(kMCA_e_map0                 )\
_op(kMCA_e_map1                 )\
_op(kMCA_e_map2                 )\
_op(kMCA_e_map3                 )\
_op(kMCA_e_cli0                 )\
_op(kMCA_e_sei0                 )\
_op(kMCA_e_clv0                 )\
_op(kMCA_e_cldsed0              )\
_op(kMCA_e_clesee0              )\
_op(kMCA_e_fetch0               )\
_op(kMCA_e_txa0                 )\
_op(kMCA_e_tya0                 )\
_op(kMCA_e_txs0                 )\
_op(kMCA_e_tay0                 )\
_op(kMCA_e_tax0                 )\
_op(kMCA_e_tsx0                 )\
_op(kMCA_e_tsy0                 )\
_op(kMCA_e_tys0                 )\
_op(kMCA_e_taz0                 )\
_op(kMCA_e_tza0                 )\
_op(kMCA_e_tab0                 )\
_op(kMCA_e_tba0                 )\
_op(kMCA_e_jmp0                 )\
_op(kMCA_e_jmpind0              )\
_op(kMCA_e_jmpindx0             )\
_op(kMCA_e_bpl                  )\
_op(kMCA_e_bmi                  )\
_op(kMCA_e_bvc                  )\
_op(kMCA_e_bvs                  )\
_op(kMCA_e_bra                  )\
_op(kMCA_e_bcc                  )\
_op(kMCA_e_bcs                  )\
_op(kMCA_e_bne                  )\
_op(kMCA_e_beq                  )\
_op(kMCA_e_braw0                )\
_op(kMCA_e_deca                 )\
_op(kMCA_e_decx                 )\
_op(kMCA_e_decy                 )\
_op(kMCA_e_decz                 )\
_op(kMCA_e_inca                 )\
_op(kMCA_e_incx                 )\
_op(kMCA_e_incy                 )\
_op(kMCA_e_incz                 )\
_op(kMCA_e_cmpai                )\
_op(kMCA_e_cmpxi                )\
_op(kMCA_e_cmpyi                )\
_op(kMCA_e_cmpzi                )\
_op(kMCA_e_ldai                 )\
_op(kMCA_e_ldxi                 )\
_op(kMCA_e_ldyi                 )\
_op(kMCA_e_ldzi                 )\
_op(kMCA_e_adci                 )\
_op(kMCA_e_sbci                 )\
_op(kMCA_e_orai                 )\
_op(kMCA_e_andi                 )\
_op(kMCA_e_eori                 )\
_op(kMCA_e_biti                 )\
_op(kMCA_e_asl_a                )\
_op(kMCA_e_rol_a                )\
_op(kMCA_e_lsr_a                )\
_op(kMCA_e_ror_a                )\
_op(kMCA_e_asr_a                )\
_op(kMCA_e_push_p               )\
_op(kMCA_e_push_a               )\
_op(kMCA_e_push_x               )\
_op(kMCA_e_push_y               )\
_op(kMCA_e_push_z               )\
_op(kMCA_e_pull0                )\
_op(kMCA_e_jsr0                 )\
_op(kMCA_e_bsr0                 )\
_op(kMCA_e_rts0                 )\
_op(kMCA_e_rti0                 )\
_op(kMCA_e_jsrind0              )\
_op(kMCA_e_jsrindx0             )\
_op(kMCA_e_rtn0                 )\
_op(kMCA_e_inw0                 )\
_op(kMCA_e_dew0                 )\
_op(kMCA_e_asw0                 )\
_op(kMCA_e_row0                 )\
_op(kMCA_e_phwi0                )\
_op(kMCA_e_phw0                 )\
_op(kMCA_e_neg                  )\
_op(kMCA_e_addr_r_abs0          )\
_op(kMCA_e_addr_r_absx0         )\
_op(kMCA_e_addr_r_absy0         )\
_op(kMCA_e_addr_r_zp0           )\
_op(kMCA_e_addr_r_zpx0          )\
_op(kMCA_e_addr_r_zpy0          )\
_op(kMCA_e_addr_r_zpxind0       )\
_op(kMCA_e_addr_r_zpindy0       )\
_op(kMCA_e_addr_r_zpindz0       )\
_op(kMCA_e_addr_spind0          )\
_op(kMCA_e_addr_w_abs0          )\
_op(kMCA_e_addr_w_absx0         )\
_op(kMCA_e_addr_w_absy0         )\
_op(kMCA_e_addr_w_zp0_a         )\
_op(kMCA_e_addr_w_zp0_x         )\
_op(kMCA_e_addr_w_zp0_y         )\
_op(kMCA_e_addr_w_zp0_z         )\
_op(kMCA_e_addr_w_zpx0_a        )\
_op(kMCA_e_addr_w_zpx0_y        )\
_op(kMCA_e_addr_w_zpx0_z        )\
_op(kMCA_e_addr_w_zpy0_x        )\
_op(kMCA_e_addr_w_zpxind0       )\
_op(kMCA_e_addr_w_zpindy0       )\
_op(kMCA_e_addr_w_zpindz0       )\
\
_op(kMCA_e_jmp1                 )\
_op(kMCA_e_jmpind1              )\
_op(kMCA_e_jmpind2              )\
_op(kMCA_e_jmpind3              )\
_op(kMCA_e_jmpindx1             )\
_op(kMCA_e_jmpindx2             )\
_op(kMCA_e_jmpindx3             )\
_op(kMCA_e_bitm1                )\
_op(kMCA_e_mem_fetch            )\
_op(kMCA_e_push1                )\
_op(kMCA_e_jsr1                 )\
_op(kMCA_e_jsr2                 )\
_op(kMCA_e_jsr3                 )\
_op(kMCA_e_rts1                 )\
_op(kMCA_e_rts2                 )\
_op(kMCA_e_rti1                 )\
_op(kMCA_e_rti2                 )\
_op(kMCA_e_rti3                 )\
_op(kMCA_e_bsr1                 )\
_op(kMCA_e_bsr2                 )\
_op(kMCA_e_bsr3                 )\
_op(kMCA_e_jsrind1              )\
_op(kMCA_e_jsrind2              )\
_op(kMCA_e_jsrind3              )\
_op(kMCA_e_jsrind4              )\
_op(kMCA_e_jsrind5              )\
_op(kMCA_e_jsrindx1             )\
_op(kMCA_e_jsrindx2             )\
_op(kMCA_e_jsrindx3             )\
_op(kMCA_e_jsrindx4             )\
_op(kMCA_e_jsrindx5             )\
_op(kMCA_e_rtn1                 )\
_op(kMCA_e_rtn2                 )\
_op(kMCA_e_rtn3                 )\
_op(kMCA_e_rtn4                 )\
_op(kMCA_e_rtn5                 )\
_op(kMCA_e_inw1                 )\
_op(kMCA_e_inw2                 )\
_op(kMCA_e_inw3                 )\
_op(kMCA_e_dew1                 )\
_op(kMCA_e_dew2                 )\
_op(kMCA_e_dew3                 )\
_op(kMCA_e_asw1                 )\
_op(kMCA_e_asw2                 )\
_op(kMCA_e_asw3                 )\
_op(kMCA_e_asw4                 )\
_op(kMCA_e_row1                 )\
_op(kMCA_e_row2                 )\
_op(kMCA_e_row3                 )\
_op(kMCA_e_row4                 )\
_op(kMCA_e_phwi1                )\
_op(kMCA_e_phwi2                )\
_op(kMCA_e_phwi3                )\
_op(kMCA_e_phw1                 )\
_op(kMCA_e_phw2                 )\
_op(kMCA_e_phw3                 )\
_op(kMCA_e_phw4                 )\
_op(kMCA_e_phw5                 )\
_op(kMCA_e_bbr1                 )\
_op(kMCA_e_bbr2                 )\
_op(kMCA_e_bbs1                 )\
_op(kMCA_e_bbs2                 )\
_op(kMCA_e_trb1                 )\
_op(kMCA_e_tsb1                 )\
_op(kMCA_e_addr_r_abs1          )\
_op(kMCA_e_addr_r_absx1         )\
_op(kMCA_e_addr_r_absy1         )\
_op(kMCA_e_addr_r_zpxind1       )\
_op(kMCA_e_addr_r_zpxind2       )\
_op(kMCA_e_addr_w_zpxind1       )\
_op(kMCA_e_addr_w_zpxind2       )\
_op(kMCA_e_addr_r_zpindy1       )\
_op(kMCA_e_addr_r_zpindy2       )\
_op(kMCA_e_addr_w_zpindy1       )\
_op(kMCA_e_addr_w_zpindy2       )\
_op(kMCA_e_addr_r_zpindz1       )\
_op(kMCA_e_addr_r_zpindz2       )\
_op(kMCA_e_addr_w_zpindz1       )\
_op(kMCA_e_addr_w_zpindz2       )\
_op(kMCA_e_addr_spind1          )\
_op(kMCA_e_addr_spind2          )\
_op(kMCA_e_brk1                 )\
_op(kMCA_e_brk2                 )\
_op(kMCA_e_brk3                 )\
_op(kMCA_e_brk4                 )\
_op(kMCA_e_brk5                 )\
\
_op(kMCA_e_addr_r_spind3        )\
_op(kMCA_e_addr_w_abs1_a        )\
_op(kMCA_e_addr_w_abs1_x        )\
_op(kMCA_e_addr_w_abs1_y        )\
_op(kMCA_e_addr_w_abs1_z        )\
_op(kMCA_e_addr_w_absx1_a       )\
_op(kMCA_e_addr_w_absx1_y       )\
_op(kMCA_e_addr_w_absx1_z       )\
_op(kMCA_e_addr_w_absy1_a       )\
_op(kMCA_e_addr_w_absy1_x       )\
_op(kMCA_e_addr_w_spind3        )\
_op(kMCA_e_cmpa                 )\
_op(kMCA_e_cmpx                 )\
_op(kMCA_e_cmpy                 )\
_op(kMCA_e_cmpz                 )\
_op(kMCA_e_lda                  )\
_op(kMCA_e_ldx                  )\
_op(kMCA_e_ldy                  )\
_op(kMCA_e_ldz                  )\
_op(kMCA_e_adc                  )\
_op(kMCA_e_sbc                  )\
_op(kMCA_e_ora                  )\
_op(kMCA_e_and                  )\
_op(kMCA_e_eor                  )\
_op(kMCA_e_bitm0                )\
_op(kMCA_e_asl_mem0             )\
_op(kMCA_e_rol_mem0             )\
_op(kMCA_e_lsr_mem0             )\
_op(kMCA_e_ror_mem0             )\
_op(kMCA_e_asr_mem0             )\
_op(kMCA_e_pull_p               )\
_op(kMCA_e_pull_a               )\
_op(kMCA_e_pull_x               )\
_op(kMCA_e_pull_y               )\
_op(kMCA_e_pull_z               )\
_op(kMCA_e_bbr0                 )\
_op(kMCA_e_bbs0                 )\
_op(kMCA_e_trb0                 )\
_op(kMCA_e_tsb0                 )\
_op(kMCA_e_rmb0                 )\
_op(kMCA_e_smb0                 )\
_op(kMCA_e_bplw1                )\
_op(kMCA_e_bmiw1                )\
_op(kMCA_e_bvcw1                )\
_op(kMCA_e_bvsw1                )\
_op(kMCA_e_braw1                )\
_op(kMCA_e_bccw1                )\
_op(kMCA_e_bcsw1                )\
_op(kMCA_e_bnew1                )\
_op(kMCA_e_beqw1                )\
_op(kMCA_e_inc_mem0             )\
_op(kMCA_e_dec_mem0             )\
_op(kMCA_end			)

#define DEFINE_NAME(_name)	# _name,
const char *ucode_addr_names[]=
{
	__GEN_UCODE_ADDR_ENUM(DEFINE_NAME)
};

int main(int ac, char **av)
{
	size_t i, c = sizeof(ucode_addr_names)/sizeof(ucode_addr_names[0]);
	printf("localparam\n");
	for(i = 0; i < c-1; i++)
	{
		printf("    %-30s    = 8'h%02X,\n",ucode_addr_names[i],(int)i);
	}
	printf("    %-30s    = 8'h%02X;\n",ucode_addr_names[i],(int)i);
	exit(0);
}
